### ISSUE TITLE
As a user, I want to assign each agenda item to a category so that I can better organize and filter the items.

### ISSUE THREAD

**Issue by TheNotoriousGB** [TheNotoriousGB/zu-bbbearbeiten-stateless#4]
# User Story: Traktandum mit Kategorie verknüpfen

**Als** Nutzer  
**möchte ich** jedes Traktandum einer Kategorie zuordnen können,  
**damit ich** die Traktanden besser organisieren und filtern kann.

## Akzeptanzkriterien:

|     Given      |       When        |          Then          |
| :------------: | :---------------: | :--------------------: |
| Ein Traktandum ist in der Applikation angelegt | Der Nutzer fügt eine Kategorie zum Traktandum hinzu | Das Traktandum ist nun mit der ausgewählten Kategorie verknüpft |
| Der Nutzer wählt eine Kategorie aus | Der Nutzer speichert das Traktandum | Das Traktandum wird unter der ausgewählten Kategorie angezeigt |
| Das Traktandum ist einer Kategorie zugeordnet | Der Nutzer filtert nach Kategorien | Nur Traktanden der gewählten Kategorie werden angezeigt |

## Subtasks:
- [x] Erstellen einer neuen Issue für die User Story
- [ ] Erstellen eines neuen Branches auf GitHub
- [ ] Testfall für das Hinzufügen einer Kategorie zu einem Traktandum in `test_helper.py` erweitern
- [ ] Implementierung der Änderungen in der Applikation
- [ ] Tests ausführen und sicherstellen, dass sie erfolgreich sind
- [ ] Änderungen committen und pushen auf den Server
- [ ] Pull-Request in den `main`-Branch erstellen

## Weitere Informationen:
Stellen Sie sicher, dass alle Tests vor dem Pushen erfolgreich ausgeführt wurden und dass der Code den bestehenden Code-Standards entspricht. Achten Sie darauf, dass die Kategorie dem Traktandum korrekt zugeordnet wird und dass alle nötigen Validierungen durchgeführt werden (z. B. Kategorie darf nicht leer sein).
